channels:
- conda-forge
dependencies:
- python=3.10.16
- pip<=25.0
- pip:
  - mlflow==2.22.0
  - cloudpickle==3.0.0
  - numpy==1.26.2
  - psutil==5.9.6
  - scikit-learn==1.3.2
  - scipy==1.11.4
name: mlflow-env
