# .github/workflows/ci.yml
name: CI Workflow

on:
  pull_request:
    branches: [ main ]

jobs:
  style-test:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - name: Setup Miniforge
        uses: conda-incubator/setup-miniconda@v2
        with:
          environment-file: env.yml
          activate-environment: fsds
          use-mamba: true
      - name: Run Flake8
        run: |
          pip install flake8
          flake8 src/


  unit-test:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - name: Setup Miniforge
        uses: conda-incubator/setup-miniconda@v2
        with:
          environment-file: env.yml
          activate-environment: fsds
          use-mamba: true
      - name: Check Conda Installation
        run: |
          echo "Checking Conda installation..."
          which conda  # This should return the path to the conda binary if it's installed
          conda --version  # This should show the version of conda
      - name: Install dependencies
        run: |
          echo "Installing dependencies..."
          python -m pip install -r requirements.txt
      - name: Install housinglib package
        run: |
          pip install .
      - name: Verify installed packages
        run: |
          conda list  # Verify that pandas and other packages are installed
      - name: Run unit tests
        run: |
          pytest tests/unit_tests/  # Run the unit tests

      - name: Run functional tests
        run: |
          pytest tests/functional_tests/  # Run the functional tests

  build:
    runs-on: ubuntu-latest
    needs: [style-test, unit-test]
    steps:
      - uses: actions/checkout@v3
      - name: Setup Miniforge
        uses: conda-incubator/setup-miniconda@v2
        with:
          environment-file: env.yml
          activate-environment: fsds
          use-mamba: true
      - name: Install tree
        run: sudo apt-get install tree
      - name: Show directory tree before build
        run: tree
      - name: Build package
        run: |
          pip install build
          python -m build
      - name: Show directory tree after build
        run: tree dist/
      - name: Upload artifacts
        uses: actions/upload-artifact@v4
        with:
          name: housinglib_artifacts
          path: |
            dist/
            env.yml


  install:
    runs-on: ubuntu-latest
    needs: build
    if: success()
    steps:
      - uses: actions/checkout@v3
      - name: Download artifacts
        uses: actions/download-artifact@v4
        with:
          name: housinglib_artifacts
      - name: Setup Miniforge
        uses: conda-incubator/setup-miniconda@v2
        with:
          environment-file: env.yml
          activate-environment: fsds
          use-mamba: true
      - name: Install built package
        run: |
          python -m pip install -r requirements.txt
          pip install dist/*.whl
      - name: Run workflow scripts with logging
        run: |
          python scripts/ingest_data.py --log_level DEBUG
          python scripts/train.py --log_level DEBUG
          python scripts/score.py --log_level DEBUG
  drift-check:
    runs-on: ubuntu-latest
    needs: install  # Ensure it's run after successful install
    if: success()
    steps:
      - uses: actions/checkout@v3

      - name: Setup Miniforge
        uses: conda-incubator/setup-miniconda@v2
        with:
          environment-file: env.yml
          activate-environment: fsds
          use-mamba: true

      - name: Install requirements
        run: |
          pip install -r requirements.txt
          pip install .  # install housinglib if not already

      - name: Run drift check
        run: |
          python scripts/monitoring.py --log_level DEBUG --no_console_log False

      - name: Upload drift report
        uses: actions/upload-artifact@v4
        with:
          name: drift-report
          path: reports/drift_report.html


